### ISSUE TITLE
Maintenance

### ISSUE THREAD

**Issue by goto-bus-stop** [browserify/node-browser-resolve#95]
Hi @defunctzombie, this module is heavily used by browserify and we'd like to do some updates (like bumping the `resolve` dependency). I understand you're not actively working on this package and I'd be happy to maintain it for the foreseeable future. Would you be open to transfering it to the @browserify org? Thanks!

**Comment by defunctzombie** [comment]
Sure - what do I need to do to make that happen?

**Comment by goto-bus-stop** [comment]
Great, we have some migration docs here: https://github.com/browserify/admin#adding-a-package-to-the-browserify-org

> To add a package to the browserify org, you will need to transfer ownership on github as well as add the package to the browserify org on npm.
>
> For github:
> 
> Visit the project page settings for a github user $USER and a project name $PROJECT at:
>
> https://github.com/defunctzombie/node-browser-resolve/settings
>
> At the bottom in the "danger zone" box, click "transfer ownership".
> 
> Type the name of the repository to confirm and below that box, type "browserify" in the field labeled "new owner's github username or organization name".
> 
> For npm, run this command, replacing $PKGNAME with the name of the package on npm:
> 
> ```
> npx npm@6.5 access grant read-write browserify:developers browser-resolve
> ```
> 
> (An old version of npm is required because recent versions of npm prohibit orgs from managing unscoped packages.)

all that's required is transferring the github repository to the org and then granting access to the npm package to the browserify org. The `npm access` command can be a bit finicky in my experience so if it doesn't immediately work you can also add me as an owner using
```
npm owner add goto-bus-stop browser-resolve
```
and then i can figure it out from there. Thanks!

**Comment by defunctzombie** [comment]
I've transferred the repo to the browserify org and granted `goto-bus-stop` owner access to the `browser-resolve` package. Thank you for picking up maintenance of this module.

**Comment by goto-bus-stop** [comment]
Thank you!
